INSERT INTO simulator (id, version, type, created_at)
VALUES
    (1, 0, 'ASSETTO_CORSA', CURRENT_TIMESTAMP),
    (2, 0, 'ASSETTO_CORSA_COMPETIZIONE', CURRENT_TIMESTAMP),
    (3, 0, 'WRC_GENERATIONS', CURRENT_TIMESTAMP);
