
-- perform cleanup of all entities after public.flyway_schema_history table truncation/deletion
drop table if exists participant cascade;
drop table if exists challenge cascade;
drop table if exists track cascade;
drop table if exists car cascade;
drop table if exists authorities cascade;
drop table if exists users cascade;

-- business model

create table car (
    id integer generated by default as identity not null,
    version integer not null,
    brand varchar(50) not null,
    name varchar(100) not null,
    horse_power integer,
    torque integer,
    wheel_drive varchar(255),
    brand_search varchar(100) not null,
    name_search varchar(100) not null,
    primary key (id)
);

create table track (
    id integer generated by default as identity not null,
    version integer not null,
    country varchar(100),
    name varchar(100) not null,
    length_km real,
    country_search varchar(100),
    name_search varchar(100) not null,
    primary key (id)
);

create table challenge (
    id integer generated by default as identity not null,
    version integer not null,
    end_date date,
    track_id integer,
    car_id integer,
    primary key (id),
    constraint FK_challenge_track foreign key (track_id) references track,
    constraint FK_challenge_car foreign key (car_id) references car
);

create table participant (
    id integer generated by default as identity not null,
    version integer not null,
    name varchar(100) not null,
    best_lap_time interval,
    challenge_id integer not null,
    name_search varchar(100) not null,
    primary key (id),
    constraint FK_participant_challenge foreign key (challenge_id) references challenge
);

-- security model

create table users (
    username varchar(100) not null,
    password varchar(500) not null,
    enabled boolean not null,

    constraint pk_users primary key (username)
);

create table authorities (
    username varchar(100) not null,
    authority varchar(50) not null,

    constraint pk_authorities primary key (username, authority),
    constraint fk_authorities_users foreign key (username) references users (username) on delete cascade
);


-- inject master user login
insert into users (username, password, enabled) values ('owner', '$2a$10$toYAwq3qrvsZVemkgKApLuBRf8EhvpBJrVaCW/CYbs.3KDx1hHRHK', true);
insert into authorities (username, authority) values ('owner', 'ADMIN');


